services:
  web:
    build: .
    container_name: ink_studio
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/app
    
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        
  
  
 