# Generated by Django 5.2 on 2025-05-13 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_shop', '0003_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistavailability',
            name='artist',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='tattoo_shop_artist__73a213_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='artist',
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session_date', 'start_time'], name='tattoo_shop_session_6fc643_idx'),
        ),
        migrations.DeleteModel(
            name='ArtistAvailability',
        ),
    ]
