# Generated by Django 5.2 on 2025-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_shop', '0004_remove_artistavailability_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
