# Generated by Django 5.2 on 2025-06-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_shop', '0005_alter_gallery_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
